### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by amoffat** [Chaosthebot/Chaos#116]
Any docker experts want to whip up a Trusty docker image with python3.6 that sets up a somewhat working env for people to test on?

**Comment by patricknelson** [comment]
I already got a Vagrantfile.

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
  config.vm.network "private_network", ip: "192.168.33.10"

  # Shared folder, just use /vagrant default (virtualbox style).
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
```

**Comment by patricknelson** [comment]
Unfortunately with all the PR's queued up (and since this is pure chaos), it's hard to refactor the system such that you can perform local development without having actual credentials setup with a real github account and repo 😢

**Comment by amoffat** [comment]
Very cool.  I think we can support both systems for different preferences

**Comment by philipz** [comment]
I have add Dockerfile #119, but follow chaos rule I don't make sure it works.

**Comment by amoffat** [comment]
Expanded the dockerfile into a dev env https://github.com/chaosbot/chaos/pull/231
