### ISSUE TITLE
Feature Request: Keep track of error logs

### ISSUE THREAD

**Issue by rudehn** [Chaosthebot/Chaos#122]
Just as the title implies. If something crashes (minor exceptions) then we simply log the error and it will show up on another page hosted from the web server. This way we can fix some of these bugs without having to get the server creator to manually tell us what went wrong.

This would require some smarter exception handling, and obviously wouldn't catch anything like syntax errors. Even still catching run time errors could prove useful for everybody's sanity

**Comment by ECrownofFire** [comment]
I think it should instead create a GitHub issue, because the web server will sometimes break. It'd need to check for duplicates somehow, maybe by checking the line that the exception came from.

**Comment by mrhwick** [comment]
ChaosBot could create an issue with a link to the github repository (at current latest commit), at the line number in whichever file.

**Comment by rudehn** [comment]
That's a great idea. Keeping a single Github Issue solely for chaosbot errors would be interesting. I haven't checked to see how the API supports creating and editing of issues.

**Comment by amoffat** [comment]
this should help for the moment http://chaosthebot.com:8081/

they're served by nginx, so they should always be around, even in chaosbot crashes
