### ISSUE TITLE
Feature Request: Repo Description

### ISSUE THREAD

**Issue by yet-another-account** [Chaosthebot/Chaos#171]
I think that there should be a description.txt file that is used to update the repo description from the code. That way we can change it via a PR.

**Comment by davidak** [comment]
I think it would be good to leave it as is so new visitors know what this was before it sank into total chaos.

Otherwise it might be important to represent what this project is currently doing. So have it changable. Not sure...

**Comment by yet-another-account** [comment]
Well, we should make a PR for it and see what people think. I just have no idea how to python so I can't actually do it myself, but I'll upvote anyone who does.

**Comment by davidak** [comment]
It is now added to the wiki: https://github.com/chaosbot/chaos/wiki/Feature-Requests

**Comment by viktorsec** [comment]
It is now implemented. https://github.com/chaosbot/Chaos/pull/268
