### ISSUE TITLE
Timeout in restart_homepage script

### ISSUE THREAD

**Issue by hongaar** [Chaosthebot/Chaos#175]
The `restart_homepage.py` needs some tinkering:
http://docs.python-requests.org/en/master/user/quickstart/#timeouts

But I won't do a push before it's alive again 

_note to self_: change line 12 to `html = requests.get("http://chaosthebot.com/", timeout=30).text`

Will create PR later

**Comment by ECrownofFire** [comment]
Using requests in this manner just throws an exception if the server is down and restarts the whole bot, so it needs to be wrapped in `try ... except` anyway.

**Comment by hongaar** [comment]
Leaving this for somebody else to pick up... Not really my specialty 😉 
And who knows... maybe this is already fixed?
/cc @amoffat
