### ISSUE TITLE
Bug in counting votes

### ISSUE THREAD

**Issue by hongaar** [Chaosthebot/Chaos#197]
According to the data files, there should be more positive votes in this PR. (It's not the 30s lag, I checked that).

#194:

![image](https://cloud.githubusercontent.com/assets/205834/26424939/51a40bde-40d3-11e7-9b0f-b7d93c8a5d31.png)

**Comment by ybart** [comment]
Maybe it counts voters rather than votes ? Did not checked the code.

**Comment by reddraggone9** [comment]
The 🎉 and ❤️ reactions were added by users who also voted with 👍. No bugs there, it just doesn't count duplicates.

**Comment by hongaar** [comment]
The code is smarter than me.
