### ISSUE TITLE
Give PR author power to postpone pending merge

### ISSUE THREAD

**Issue by ozyx** [Chaosthebot/Chaos#229]
Earlier I had a PR which was approved for merge, but which contained some mistakes. I wasn't able to fix it in time and it was merged into the codebase. It would be nice to be able to postpone the pending merge of a PR, perhaps using some kind of keyword which ChaosBot can parse. That way if a dev is AFK but planning on fixing a PR they won't have to close and reopen.

Something like...
`#delay` - delay evaluation of a PR by some duration defined by ChaosBot
`$delay`
`!delay`

This could be posted as a comment in the PR.

**Comment by hongaar** [comment]
It's already possible, just use the WIP keyword in the PRs title.

**Comment by ozyx** [comment]
That works...
