### ISSUE TITLE
Fix Chaosbot merging in errors

### ISSUE THREAD

**Issue by rudehn** [Chaosthebot/Chaos#249]
Why don't we simply set up a dev branch on the server?

When we go to pull a new PR.

1. Swap to dev branch
2. Pull code
3. Test for syntax error
4. Checks Pass? Merge back to master

While this approach wouldn't revert changes, it could still give the opportunity for us to recover from any errors, and allow us to submit PRs for fixing any bugs

**Comment by while-loop** [comment]
Why not set chaos with Travis and restrict the bot from merging any failed Travis builds
