### ISSUE TITLE
Introducing quasi-dictatorship

### ISSUE THREAD

**Issue by rudehn** [Chaosthebot/Chaos#254]
So here's an interesting idea. Currently everyone's vote carries equal weight, but what if this wasn't the case?

**Proposition:** Each time a PR is merged into the codebase, a new "dictator" is chosen. This dictator's vote will carry more weight (2x, 5x, 10x, etc) for the duration until a new pull request is merged in. Any PR that the dictator voted on during their reign will keep their weighted vote. So if a dictator voted on a PR, and a new dictator voted on the same PR, there would be 2 weighted votes for that PR.

Alternatively, we could introduce the concept of the peasant 😂, which would be the opposite of a dictator (.5x, .2x, .1x) or both! 

Thoughts?

**Comment by PlasmaPower** [comment]
How would the "dictator" be chosen? Why?

**Comment by rudehn** [comment]
My thoughts were the server would randomly choose a person from either people that have voted, submitted PRs, watching the repo etc.

The fun part is there doesn't have to be an announcement on who the dictator is. 

As for why? Why not? It's just a new idea to keep things fresh.
