### ISSUE TITLE
Propose TODOLIST

### ISSUE THREAD

**Issue by eamanu** [Chaosthebot/Chaos#270]
We can make a todolist.md to put some ideas or challenges to do.

**Comment by reddraggone9** [comment]
Seems like that's kinda the point of issues. Or one of the points anyway.

**Comment by amoffat** [comment]
There's kind of a start of this in the [wiki](https://github.com/chaosbot/chaos/wiki/Feature-Requests) which anyone is free to edit

**Comment by viktorsec** [comment]
Agreed, it makes more sense to use wiki for this.

**Comment by eamanu** [comment]
Ok sound great use the wiki
