### ISSUE TITLE
Move to VPS Dime

### ISSUE THREAD

**Issue by just1689** [Chaosthebot/Chaos#355]
Move to VPS Dime hosting with:

4 cores
6 GB RAM
30 GB SSD
2 TB Traffic

**Comment by phil-r** [comment]
I don't think we're gonna run out of capacity any time soon

**Comment by davidak** [comment]
We could get a sponsored VM from DigitalOcean, Linode or such.

@amoffat would you appreciate that?

**Comment by amoffat** [comment]
@davidak absolutely!  We're on Linode now, 2GB plan
