### ISSUE TITLE
What does `variance` do in `get_vote_sum()`?

### ISSUE THREAD

**Issue by hongaar** [Chaosthebot/Chaos#358]
`get_vote_sum()` always returns a variance of `0` or am I missing something?

/ping @J0hn-

**Comment by flibustier** [comment]
This is to recover the gap between the number of positive votes and the average of the votes 
Exemple : 42 :+1: - 35 :-1:
Total : 7 
"Variance" : 42 (positives votes) - 7 (total) : 35
This reflect the high value of positive and negative votes, so when the threeshold is ok (7) but "variance" is high => the voting window is extended

**Comment by flibustier** [comment]
Now that I just explained it, I think it could be done differently!

**Comment by hongaar** [comment]
Ah of course a vote could be `-1`, my bad! (I blame the temperature..) 🌞
