### ISSUE TITLE
migrations

### ISSUE THREAD

**Issue by amoffat** [Chaosthebot/Chaos#38]
A couple of people ([eg](https://github.com/chaosbot/chaos/pull/27)) have made some add-hoc migrations that install dependencies.  These work now because they are [idempotent](http://www.restapitutorial.com/lessons/idempotency.html), but they won't work for more advanced installation.  Here are some thoughts on how migrations could work:

1. chaos.py imports migrations.py
2. migrations.py looks in a /migrations folder for scripts
3. migrations.py runs scripts

The piece that is missing is a good way to determine if a script has been run or not, so chaosbot can quickly determine what migrations need to be run.  Any ideas?

**Comment by ghost** [comment]
In the long run I guess we'd have to use configuration management software anyway.
This would lead to not only have control over the bot, but easily to the whole server.

**Comment by davidak** [comment]
@trqx i think that's the way to go. I suggest Ansible or SaltStack.

**Comment by OpenNingia** [comment]
I'd rather being idempotent to be a requisite of every update path.

**Comment by no-identd** [comment]
I'm 100% in favor of Ansible.

**Comment by amoffat** [comment]
we have puppet now iirc.  and there are talks of ansible coming in as well

**Comment by yunier-rojas** [comment]
I prefer Ansible. :+1:
