### ISSUE TITLE
Voting with more emojis

### ISSUE THREAD

**Issue by hongaar** [Chaosthebot/Chaos#41]
It should be possible to cast votes with more than only 👍 and 👎 . For example, ❤️  and 🎉 could be interpreted as a positive, and 😕 could be interpreted as a negative vote.

This would introduce some bias (as reactions have more positive than negative options) but that may not be a problem, as more merged PRs === more chaos.

Then what about the 😄 reaction?

**Comment by studiosi** [comment]
The psychology of emoji is very weird. For example, some of my friends consider 😄 ironical most of the times, while others interpret it as plain laughter.

One of the most controversial ones is the dancer ( 💃 ) XDDD

**Comment by jabbink** [comment]
:shipit:

**Comment by DasSkelett** [comment]
With 👍 and 👎 you have plain emojis for voting, everybody can understand. More emojis are only confusing I think.

**Comment by jabbink** [comment]
More chaos though.

**Comment by rtzoeller** [comment]
👍🏽

**Comment by golergka** [comment]
I suggest giving ambiguous emojis random meaning. More chaos.

**Comment by ghost** [comment]
:shipit:

**Comment by tusharmakkar08** [comment]
What about 🥇 ?
