### ISSUE TITLE
Meritocracy list bug ?

### ISSUE THREAD

**Issue by o3LL** [Chaosthebot/Chaos#432]
-> https://github.com/chaosbot/Chaos/pull/425#issuecomment-305189271

**Comment by PlasmaPower** [comment]
Looking into it.

**Comment by PlasmaPower** [comment]
I think you're on it - maybe the author of the PR amended the commit?

**Comment by PlasmaPower** [comment]
No, your review is on the correct commit. Hmm...

**Comment by andrewda** [comment]
http://chaosthebot.com:8081/chaos-stderr.log:

```
05-31 14:13 pull_requests INFO     generated meritocracy: {'andrewda', 'viktorsec', 'phil-r', 'plasmapower', 'smittyvb', 'rhengles', 'hongaar', 'eukaryote31', 'rudehn', 'amoffat'}
```

**Comment by andrewda** [comment]
Looks like it's only getting the top 10 voters, not contributors.

**Comment by PlasmaPower** [comment]
Odd. If I change URN to `chaosbot/chaos` locally, it works fine.

**Comment by PlasmaPower** [comment]
Odd. If I change URN to `chaosbot/chaos` locally, it works fine.

**Comment by PlasmaPower** [comment]
Oh, I forgot about the `202` responses! I'll fix it.

**Comment by PlasmaPower** [comment]
Actually, I have to go, but basically the contributors endpoint can return a 202 status, in which case GitHub hasn't cached to contributors yet but it's now working on them. After that, we should just wait 5 or 10 seconds then retry the request.

**Comment by flibustier** [comment]
A hall of fame of "meritocrats" like voters.html would be cool! :)

**Comment by PlasmaPower** [comment]
Confirmed fixed! :tada:

**Comment by Swizz** [comment]
Top contributors is about lines or commits ?

**Comment by PlasmaPower** [comment]
@Swizz currently commits

**Comment by Swizz** [comment]
This strategy promote to keep commits as small as possible

**Comment by PlasmaPower** [comment]
@Swizz no, we have squash enabled so 1 pr = 1 commit

**Comment by mdcfe** [comment]
@PlasmaPower Still, multiple small PRs give someone an advantage over fewer larger PRs.

**Comment by reddraggone9** [comment]
> multiple small PRs give someone an advantage over fewer larger PRs.

Seems like a small issue compared to how votes are counted.
