### ISSUE TITLE
GitHub API: 422 unprocessable entity

### ISSUE THREAD

**Issue by PlasmaPower** [Chaosthebot/Chaos#476]
> 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/chaosbot/Chaos/labels

http://chaosthebot.com:8081/chaos-stderr.log

We had this issue with status updates, but now it's returned in the form of label creation. Ideas?

**Comment by andrewda** [comment]
I believe that's the error it returns that when the label already exists. Let me check on that, though.

**Comment by andrewda** [comment]
Yea, we should log the response body if there's an error. It should say there. My guess is that the labels already exist. Reference: https://developer.github.com/v3/#client-errors

**Comment by PlasmaPower** [comment]
I hadn't seen the client errors page before, thanks. I'd still prefer to not log a bunch of errors, and instead list the labels once, then add missing ones. I implemented a similar solution for the blocklist PR.

**Comment by Swizz** [comment]
https://github.com/chaosbot/Chaos/pull/451#issuecomment-305423130

I am going to rework this PR, with the @hongaar ideas https://github.com/chaosbot/Chaos/pull/451#issuecomment-305489318

**Comment by mdcfe** [comment]
Will be fixed by #486.
