### ISSUE TITLE
Problem with generator of encrypted keys

### ISSUE THREAD

**Issue by eamanu** [Chaosthebot/Chaos#538]
When I try to make the sample of the  [wiki](https://github.com/chaosbot/Chaos/wiki/Encryption) I have this error:

  File "<stdin>", line 1, in <module>
  File "/home/eamanu/dev/Chaos/generate_keys_secret.py", line 1, in <module>
    from encryption import decrypt
  File "encryption.py", line 48, in <module>
    decrypt = create_decryptor("/etc/privkey", "server/pubkey.txt")
  File "encryption.py", line 14, in create_decryptor
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

Where I am wrong?

**Comment by andrewda** [comment]
Does the `server/pubkey.txt` file exist?

**Comment by PlasmaPower** [comment]
@andrewda it should be autogenerated.

@eamanu  Are you using Python 3.6?

**Comment by eamanu** [comment]
@PlasmaPower Maybe that is my problem.. I am using Python2.7

I will test it
