### ISSUE TITLE
chaosthebot.com gives a 502

### ISSUE THREAD

**Issue by dbpokorny** [Chaosthebot/Chaos#551]
502 Bad Gateway

nginx/1.4.6 (Ubuntu)

**Comment by PlasmaPower** [comment]
Same as #537? I thought it was fixed.

**Comment by PlasmaPower** [comment]
This seems permanent, it's been down for 30 minutes.

**Comment by amoffat** [comment]
Bounced it.  The chaos_server process must have died, and it isn't managed under supervisor

**Comment by mdcfe** [comment]
I can make a PR to add a Supervisor config and to make ChaosBot simply stop and restart the web server as needed.

**Comment by itsnotvalid** [comment]
Still 502.

**Comment by cooperhammond** [comment]
Still is now.

**Comment by mdcfe** [comment]
The web server may be fixed if #552 is ever merged, but this is unlikely before v2 now.

**Comment by Redmega** [comment]
We should add an index.html with a construction crew emoji.
