### ISSUE TITLE
Add http://chaosthebot.com to the repository description

### ISSUE THREAD

**Issue by wolfgang42** [Chaosthebot/Chaos#76]
Right now the link is a bit buried in the README, but since there's a web server running now there's actually content to see there.

I don't believe there's any way to do this as a PR, so I'm filing an issue instead so someone who has permission can change this manually.

**Comment by yet-another-account** [comment]
I think that we should, instead, put the repo description as a file that is updated every time it restarts, so that the description can be changed by PR in the future.

**Comment by wolfgang42** [comment]
Closed by #268 which takes advantage of a feature that's since been added.
